#!/bin/bash
#
# This program checks to see if your source code is
# up to date, using git origin branch. If there are
# changes to be pulled down then it runs a git fetch
# and exits successfully.
#
# This differs from the other executable in that you
# can run it on --bare checkouts.
#
# usage: ploy -d /path/to/gitrepo && run some other command


while getopts ":d:" opt; do
  case $opt in
    d) dir=$OPTARG ;;
   \?) echo "usage: $(basename $0) -d /path/to/gitrepo/" && exit 1 ;;
  esac
done

# check that it is a git repo
[ ! -f ${dir}/HEAD ] && [ ! -d ${dir}/info ] && echo "Not in a bare git repo" && exit 1
cd $dir
git update-server-info

# figure out what the current branch is
BRANCH=$(git symbolic-ref --short -q HEAD)
[ -z "${BRANCH}" ] && echo "Not able to detect branch, try: git checkout somebranch" && exit 1

# get remote HEAD of origin/$BRANCH
HEAD=$(git ls-remote --heads origin $BRANCH | cut -f1)

# if the commit hash of the remote HEAD doesn't exist locally, try and pull latest patches
if [ "$(git log -n1 --pretty=%H)" != "$HEAD" ]; then

  # bit different for bare repos
  git fetch -q origin +refs/*:refs/* > /dev/null
  git update-server-info

  if [ "$(git log -n1 --pretty=%H)" == "$HEAD" ]; then
    exit 0
  else
    echo "trouble fetching patches to ${dir}: git fetch origin ${BRANCH}" && exit 1
  fi
fi
exit 1
